# exporters/servuo_script_builder.py
# Generates ServUO-compatible C# script stubs for custom item graphics.
# Output: a .cs file ready to drop into a ServUO scripts directory.

import os
from typing import List
from datetime import datetime


CS_TEMPLATE = """using System;
using Server;
using Server.Items;

namespace Server.Items
{{
    // Auto-generated by UO Asset Toolkit
    // Generated: {date}
    // Source mod: {mod_name}

    public class CustomItem_{hex_id} : Item
    {{
        [Constructable]
        public CustomItem_{hex_id}() : base({item_id})
        {{
            Name = "Custom Item {hex_id}";
            Weight = 1.0;
        }}

        public CustomItem_{hex_id}(Serial serial) : base(serial)
        {{
        }}

        public override void Serialize(GenericWriter writer)
        {{
            base.Serialize(writer);
            writer.Write(0);
        }}

        public override void Deserialize(GenericReader reader)
        {{
            base.Deserialize(reader);
            int version = reader.ReadInt();
        }}
    }}
}}
"""


def build_servuo_scripts(
    item_ids: List[int],
    output_dir: str,
    mod_name: str = "Custom Shard Graphics",
) -> List[str]:
    """
    Generate a C# stub file for each item ID.
    Returns list of written file paths.
    """
    os.makedirs(output_dir, exist_ok=True)
    written = []
    date_str = datetime.now().strftime("%Y-%m-%d")

    for item_id in item_ids:
        hex_id = f"{item_id:04X}"
        content = CS_TEMPLATE.format(
            date=date_str,
            mod_name=mod_name,
            hex_id=hex_id,
            item_id=item_id,
        )
        filename = f"CustomItem_{hex_id}.cs"
        path = os.path.join(output_dir, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        written.append(path)

    print(f"[ServUO] Generated {len(written)} C# scripts -> {output_dir}")
    return written
